ROOPANTOR_AROOP_PARSER_CSOURCES=$(wildcard $(ROOPANTOR_HOME)/libs/aroopp/vsrc/*.c)
ROOPANTOR_AROOP_PARSER_VSOURCE_BASE=$(basename $(notdir $(ROOPANTOR_AROOP_PARSER_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPANTOR_HOME)/build/.objects/, $(addsuffix .o,$(ROOPANTOR_AROOP_PARSER_VSOURCE_BASE)))
