ROOPANTOR_PARSER_FOR_VALA_LANG_CSOURCES=$(wildcard $(ROOPANTOR_HOME)/libs/valaparse/vsrc/*.c)
ROOPANTOR_PARSER_FOR_VALA_LANG_VSOURCE_BASE=$(basename $(notdir $(ROOPANTOR_PARSER_FOR_VALA_LANG_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPANTOR_HOME)/build/.objects/, $(addsuffix .o,$(ROOPANTOR_PARSER_FOR_VALA_LANG_VSOURCE_BASE)))
